import Vue from 'vue';
import Vuetify from 'vuetify/lib/framework';

Vue.use(Vuetify);

const vuetify = new Vuetify({
    theme:{
        themes: {
        light: {
            background: '#ede6ec',
            surface: '#fff7fd',
            'surface-dim': '#cbc4ca',
            'surface-bright': '#fff7fd',
            'surface-container-lowest': '#ffffff',
            'surface-container-low': '#f9f1f8',
            'surface-container': '#ede6ec',
            'surface-container-high': '#e2dbe1',
            'surface-container-highest': '#d6cfd6',
            'on-surface': '#131014',
            'inverse-surface': '#332f34',
            'inverse-on-surface': '#f6eef5',
            outline: '#57505a',
            'outline-variant': '#726a75',
            primary: '#472764',
            'on-primary': '#ffffff',
            'primary-container': '#815f9f',
            'on-primary-container': '#ffffff',
            'inverse-primary': '#deb7ff',
            secondary: '#29306e',
            'on-secondary': '#ffffff',
            'secondary-container': '#6168a9',
            'on-secondary-container': '#ffffff',
            tertiary: '#58214c',
            'on-tertiary': '#ffffff',
            'tertiary-container': '#985886',
            'on-tertiary-container': '#ffffff',
            error: '#740006',
            'on-error': '#ffffff',
            'error-container': '#cf2c27',
            'on-error-container': '#ffffff',
            'primary-fixed': '#815f9f',
            'primary-fixed-dim': '#674685',
            'on-primary-fixed': '#ffffff',
            'on-primary-fixed-variant': '#ffffff',
            'secondary-fixed': '#6168a9',
            'secondary-fixed-dim': '#484f8f',
            'on-secondary-fixed': '#ffffff',
            'on-secondary-fixed-variant': '#ffffff',
            'tertiary-fixed': '#985886',
            'tertiary-fixed-dim': '#7c406c',
            'on-tertiary-fixed': '#ffffff',
            'on-tertiary-fixed-variant': '#ffffff',
            'surface-light': '#ede6ec',
            variables: {
            'overlay-background': '#1f1a22',
            },
        },
        dark: {
            background: '#2a272b',
            surface: '#151217',
            'surface-dim': '#151217',
            'surface-bright': '#474348',
            'surface-container-lowest': '#09070a',
            'surface-container-low': '#1f1c21',
            'surface-container': '#2a272b',
            'surface-container-high': '#353136',
            'surface-container-highest': '#403c41',
            'on-surface': '#ffffff',
            'inverse-surface': '#e8e0e7',
            'inverse-on-surface': '#2c292e',
            outline: '#b8afbb',
            'outline-variant': '#968d99',
            primary: '#edd3ff',
            'on-primary': '#351552',
            'primary-container': '#472764',
            'on-primary-container': '#f1dbff',
            'inverse-primary': '#5a3977',
            secondary: '#d8daff',
            'on-secondary': '#171e5c',
            'secondary-container': '#29306e',
            'on-secondary-container': '#dfe0ff',
            tertiary: '#ffceed',
            'on-tertiary': '#440f3a',
            'tertiary-container': '#58214c',
            'on-tertiary-container': '#ffd7ef',
            error: '#ffd2cc',
            'on-error': '#540003',
            'error-container': '#740006',
            'on-error-container': '#ffd2cc',
            'primary-fixed': '#f1dbff',
            'primary-fixed-dim': '#deb7ff',
            'on-primary-fixed': '#1e0038',
            'on-primary-fixed-variant': '#472764',
            'secondary-fixed': '#dfe0ff',
            'secondary-fixed-dim': '#bdc2ff',
            'on-secondary-fixed': '#000448',
            'on-secondary-fixed-variant': '#29306e',
            'tertiary-fixed': '#ffd7ef',
            'tertiary-fixed-dim': '#fbafe3',
            'on-tertiary-fixed': '#280021',
            'on-tertiary-fixed-variant': '#58214c',
            'surface-light': '#3c383d',
            variables: {
            'overlay-background': '#1f1a22',
            },
        },
        },
    }
  });

export default vuetify;
